In [2]:
import torch

labels = torch.tensor([1, 2, -1, -1])
sim = torch.rand(4, 4)
global_R = torch.full((labels.size(0), labels.size(0)), -1.0)
mask_label = (labels != -1)
label_mask = mask_label.unsqueeze(0) & mask_label.unsqueeze(1)
label_R = (labels.unsqueeze(0) == labels.unsqueeze(1)).float()
global_R[label_mask] = label_R[label_mask]

print(mask_label.unsqueeze(0), '\n', mask_label.unsqueeze(1))
print(global_R)

tensor([[ True,  True, False, False]]) 
 tensor([[ True],
        [ True],
        [False],
        [False]])
tensor([[ 1.,  0., -1., -1.],
        [ 0.,  1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.]])


从上面的输出结果可以看到，`.unsqueeze()`是在指定参数上增加维度

In [3]:
other_mask = ~label_mask
l, u = 0.5, 0.9
global_R[other_mask & (sim >= u)] = torch.tensor(1.0)
global_R[other_mask & (sim <= l)] = torch.tensor(0.0)
print(sim)
print(global_R)

tensor([[0.6492, 0.4178, 0.8429, 0.9125],
        [0.7845, 0.0042, 0.6734, 0.1992],
        [0.1857, 0.5591, 0.9462, 0.7340],
        [0.7992, 0.5766, 0.3201, 0.8229]])
tensor([[ 1.,  0., -1.,  1.],
        [ 0.,  1., -1.,  0.],
        [ 0., -1.,  1., -1.],
        [-1., -1.,  0., -1.]])


In [4]:
uncert_mask = (global_R == -1)
mask = torch.tril(uncert_mask, diagonal=-1)
row, col = torch.where(mask)
uncert_ij = torch.stack([row, col], dim=1).tolist()
print(uncert_ij)

[[2, 1], [3, 0], [3, 1]]


## 1010
- 学习`unsqueeze()`